### ISSUE TITLE
More information needed

### ISSUE THREAD

**Issue by kamkarthi** [antnks/technicolor-config-decrypt#2]
Hi,

I'm no good working with binary files, so just following steps for decrypting.
I got stuck with third step in regards to FILE-SIZE-MINUS-20-MINUS-262. 
The file size in my  router export is as below.
$ du config.bin
212     config.bin

Please show me how to calculate its value?

dd if=config.bin bs=1 count=246 > header.txt
dd if=config.bin bs=1 skip=246 count=16 > iv.bin
dd if=config.bin bs=1 skip=262 count=FILE-SIZE-MINUS-20-MINUS-262 > config.aes
openssl enc -aes-256-cbc -nosalt -d -in config.aes \
-K '72ab46c7e90c66feb4af261437bd738204c640dc7f0b9959ea18d582b6876783' -iv 'c6b1c0aac15c13e5ab18a8aabafc14e0'

**Comment by antnks** [comment]
Your config is just 212 bytes? That's too small
